name: "FAP: Build and Lint"

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    name: "Build & Lint FAP"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          task: lint

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: theme-manager-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

  release:
    needs: build-and-lint
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: "Create Release"
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: theme-manager-release
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
          generate_release_notes: true
