name: "FAP: Build and Lint"

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  ufbt-build:
    runs-on: ubuntu-latest
    name: "Build FAP"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: theme-manager-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

  ufbt-lint:
    runs-on: ubuntu-latest
    name: "Lint sources"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          app-dir: theme_manager
          task: lint

  release:
    needs: ufbt-build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: "Create Release"
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-release
        with:
          sdk-channel: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.build-release.outputs.fap-artifacts }}
          generate_release_notes: true
